# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: duplexer_ipc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64uplexer_ipc.proto\x12\x08\x64uplexer\"\x87\x01\n\x0cPrintRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x12\n\nnum_copies\x18\x04 \x01(\x05\x12\x0f\n\x07options\x18\x05 \x01(\t\x12\x17\n\x0fvirtual_printer\x18\x06 \x01(\t\x12\x0c\n\x04\x66ile\x18\x07 \x01(\x0c\x62\x06proto3')



_PRINTREQUEST = DESCRIPTOR.message_types_by_name['PrintRequest']
PrintRequest = _reflection.GeneratedProtocolMessageType('PrintRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRINTREQUEST,
  '__module__' : 'duplexer_ipc_pb2'
  # @@protoc_insertion_point(class_scope:duplexer.PrintRequest)
  })
_sym_db.RegisterMessage(PrintRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRINTREQUEST._serialized_start=33
  _PRINTREQUEST._serialized_end=168
# @@protoc_insertion_point(module_scope)
